# Generated by Django 2.2 on 2022-06-01 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=255, verbose_name='user agent')),
                ('force_key_update_counter', models.PositiveSmallIntegerField(default=0, help_text='counter of unplanned key regenerations')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='access_protection.Device')),
            ],
            options={
                'verbose_name': 'device IP',
                'verbose_name_plural': 'device IPs',
            },
        ),
        migrations.CreateModel(
            name='ReportEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'report email',
                'verbose_name_plural': 'report emails',
            },
        ),
        migrations.CreateModel(
            name='DeviceLoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='session start')),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=True, verbose_name='is success')),
                ('comment', models.TextField(default='')),
                ('device_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_log', to='access_protection.DeviceIP', verbose_name='device ip')),
            ],
            options={
                'verbose_name': 'device login history',
                'verbose_name_plural': 'device login history',
            },
        ),
        migrations.CreateModel(
            name='DeviceKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('datetime_deactivated', models.DateTimeField(null=True, verbose_name='deactivated at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='access_protection.Device')),
            ],
            options={
                'verbose_name': 'device key',
                'verbose_name_plural': 'device keys',
                'get_latest_by': 'datetime_created',
            },
        ),
        migrations.CreateModel(
            name='DeviceEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Add'), (1, 'Enable'), (2, 'Disable')], verbose_name='event type')),
                ('comment', models.TextField(default='')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_log', to='access_protection.Device')),
                ('user', models.ForeignKey(help_text='user who initiated the event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_events_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device events log',
                'verbose_name_plural': 'device event',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='last_login_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_protection.DeviceLoginLog'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
